const ICON_PATH = '/icons/skills';

export const SKILL_BRAND_COLORS: Record<string, string> = {
  'React': '#61DAFB',
  'TypeScript': '#3178C6',
  'JavaScript': '#F7DF1E',
  'HTML5': '#E34F26',
  'CSS': '#1572B6',
  'CSS3': '#1572B6',
  'Vite': '#646CFF',
  'Redux Toolkit': '#764ABC',
  'Redux': '#764ABC',
  'React Query': '#FF4154',
  'React Router': '#CA4245',
  'Material UI': '#007FFF',
  'SASS': '#CC6699',
  'SASS/CSS': '#CC6699',
  'Styled Components': '#DB7093',
  'Playwright': '#2EAD33',
  'Jest': '#C21325',
  'Testing Library': '#E33332',
  'MSW': '#FF6A33',
  'Vitest': '#6E9F18',
  'Git': '#F05032',
  'GitHub Actions': '#2088FF',
  'Webpack': '#8DD6F9',
  'ESLint': '#4B32C3',
  'Prettier': '#F7B93E',
  'Husky': '#42B983',
  'React Native': '#61DAFB',
  'Expo': '#000020',
  'Node.js': '#339933',
  'MongoDB': '#47A248',
  'REST API': '#009688',
  'Firebase': '#FFCA28',
  'Lexical': '#2962FF',
  'DnD Kit': '#6C63FF',
  'AWS Cognito': '#DD344C',
  'OIDC': '#F78C40',
  'WebAuthn': '#3DDC84',
  'ReactFlow': '#FF0072',
  'Unity': '#222C37',
  'Photoshop': '#31A8FF',
  'Illustrator': '#FF9A00',
  'After Effects': '#9999FF',
  'Blender': '#F5792A',
  'Maya': '#149ECA',
  'WebStorm': '#07C3F2',
  'Visual Studio': '#5C2D91',
  'SJCL': '#8BC34A',
  'QR / WebAuthn': '#3DDC84',
  'TensorFlow': '#FF6F00',
  'Adyen Payment System': '#0ABF53',
  'jQuery': '#0769AD',
  'Web Development': '#4CAF50',
};

export const DUAL_ICONS: Record<string, { mono: string; hover: string }> = {
  'Vite': { mono: `${ICON_PATH}/vite-mono.svg`, hover: `${ICON_PATH}/vite-svgrepo-com.svg` },
  'React Query': { mono: `${ICON_PATH}/react-query-mono.svg`, hover: `${ICON_PATH}/react-query-red.svg` },
};

export const SKILL_ICON_MAP: Record<string, string> = {
  'React': `${ICON_PATH}/react-svgrepo-com.svg`,
  'TypeScript': `${ICON_PATH}/typescript-16-svgrepo-com.svg`,
  'JavaScript': `${ICON_PATH}/javascript-16-svgrepo-com.svg`,
  'HTML5': `${ICON_PATH}/html5-01-svgrepo-com.svg`,
  'CSS': `${ICON_PATH}/css3-svgrepo-com.svg`,
  'CSS3': `${ICON_PATH}/css3-svgrepo-com.svg`,
  'Vite': `${ICON_PATH}/vite-svgrepo-com.svg`,
  'Redux Toolkit': `${ICON_PATH}/redux-fill-svgrepo-com.svg`,
  'Redux': `${ICON_PATH}/redux-fill-svgrepo-com.svg`,
  'React Query': `${ICON_PATH}/React-Query-Icon--Streamline-Svg-Logos.svg`,
  'React Router': `${ICON_PATH}/React-Router--Streamline-Svg-Logos.svg`,
  'Material UI': `${ICON_PATH}/material-ui-svgrepo-com.svg`,
  'SASS': `${ICON_PATH}/sass-svgrepo-com.svg`,
  'SASS/CSS': `${ICON_PATH}/sass-svgrepo-com.svg`,
  'Styled Components': `${ICON_PATH}/styled-components.svg`,
  'Playwright': `${ICON_PATH}/playwright.svg`,
  'Jest': `${ICON_PATH}/jest.svg`,
  'Testing Library': `${ICON_PATH}/testing-library.svg`,
  'MSW': `${ICON_PATH}/msw.svg`,
  'Vitest': `${ICON_PATH}/vitest.svg`,
  'Git': `${ICON_PATH}/git-svgrepo-com.svg`,
  'GitHub Actions': `${ICON_PATH}/github-142-svgrepo-com.svg`,
  'Webpack': `${ICON_PATH}/webpack.svg`,
  'ESLint': `${ICON_PATH}/eslint-16-svgrepo-com.svg`,
  'Prettier': `${ICON_PATH}/prettier-svgrepo-com.svg`,
  'Husky': `${ICON_PATH}/husky.svg`,
  'React Native': `${ICON_PATH}/react-native.svg`,
  'Expo': `${ICON_PATH}/expo.svg`,
  'Node.js': `${ICON_PATH}/Nodejs-Icon--Streamline-Svg-Logos.svg`,
  'MongoDB': `${ICON_PATH}/Mongodb-Icon--Streamline-Svg-Logos.svg`,
  'REST API': `${ICON_PATH}/rest-api.svg`,
  'Firebase': `${ICON_PATH}/firebase.svg`,
  'Lexical': `${ICON_PATH}/lexical.svg`,
  'DnD Kit': `${ICON_PATH}/dnd-kit.svg`,
  'AWS Cognito': `${ICON_PATH}/aws-cognito.svg`,
  'OIDC': `${ICON_PATH}/oidc.svg`,
  'WebAuthn': `${ICON_PATH}/webauthn.svg`,
  'ReactFlow': `${ICON_PATH}/reactflow.svg`,
  'Unity': `${ICON_PATH}/unity.svg`,
  'Photoshop': `${ICON_PATH}/photoshop-svgrepo-com.svg`,
  'Illustrator': `${ICON_PATH}/adobe-illustrator-svgrepo-com.svg`,
  'After Effects': `${ICON_PATH}/aftereffects-svgrepo-com.svg`,
  'Blender': `${ICON_PATH}/blender-svgrepo-com.svg`,
  'Maya': `${ICON_PATH}/Maya-Logo--Streamline-Ultimate.png`,
  'WebStorm': `${ICON_PATH}/webstorm-svgrepo-com.svg`,
  'Visual Studio': `${ICON_PATH}/visual-studio.svg`,
  'SJCL': `${ICON_PATH}/sjcl.svg`,
  'QR / WebAuthn': `${ICON_PATH}/webauthn.svg`,
  'TensorFlow': `${ICON_PATH}/tensorflow.svg`,
  'Adyen Payment System': `${ICON_PATH}/adyen.svg`,
  'jQuery': `${ICON_PATH}/jquery.svg`,
  'Web Development': `${ICON_PATH}/web-dev.svg`,
};
