const ICON_PATH = '/icons/skills';

export const SKILL_ICON_MAP: Record<string, string> = {
  'React': `${ICON_PATH}/react-svgrepo-com.svg`,
  'TypeScript': `${ICON_PATH}/typescript-16-svgrepo-com.svg`,
  'JavaScript': `${ICON_PATH}/javascript-16-svgrepo-com.svg`,
  'HTML5': `${ICON_PATH}/html5-01-svgrepo-com.svg`,
  'CSS': `${ICON_PATH}/css3-svgrepo-com.svg`,
  'CSS3': `${ICON_PATH}/css3-svgrepo-com.svg`,
  'Vite': `${ICON_PATH}/vite-svgrepo-com.svg`,
  'Redux Toolkit': `${ICON_PATH}/redux-logo-svgrepo-com.svg`,
  'Redux': `${ICON_PATH}/redux-logo-svgrepo-com.svg`,
  'React Query': `${ICON_PATH}/React-Query-Icon--Streamline-Svg-Logos.svg`,
  'React Router': `${ICON_PATH}/React-Router--Streamline-Svg-Logos.svg`,
  'Material UI': `${ICON_PATH}/material-ui-svgrepo-com.svg`,
  'SASS': `${ICON_PATH}/sass-svgrepo-com.svg`,
  'SASS/CSS': `${ICON_PATH}/sass-svgrepo-com.svg`,
  'Styled Components': `${ICON_PATH}/styled-components.svg`,
  'Playwright': `${ICON_PATH}/playwright.svg`,
  'Jest': `${ICON_PATH}/jest.svg`,
  'Testing Library': `${ICON_PATH}/testing-library.svg`,
  'MSW': `${ICON_PATH}/msw.svg`,
  'Vitest': `${ICON_PATH}/vitest.svg`,
  'Git': `${ICON_PATH}/git-svgrepo-com.svg`,
  'GitHub Actions': `${ICON_PATH}/github-142-svgrepo-com.svg`,
  'Webpack': `${ICON_PATH}/webpack.svg`,
  'ESLint': `${ICON_PATH}/eslint-16-svgrepo-com.svg`,
  'Prettier': `${ICON_PATH}/prettier-svgrepo-com.svg`,
  'Husky': `${ICON_PATH}/husky.svg`,
  'React Native': `${ICON_PATH}/react-native.svg`,
  'Expo': `${ICON_PATH}/expo.svg`,
  'Node.js': `${ICON_PATH}/Nodejs-Icon--Streamline-Svg-Logos.svg`,
  'MongoDB': `${ICON_PATH}/Mongodb-Icon--Streamline-Svg-Logos.svg`,
  'REST API': `${ICON_PATH}/rest-api.svg`,
  'Firebase': `${ICON_PATH}/firebase.svg`,
  'Lexical': `${ICON_PATH}/lexical.svg`,
  'DnD Kit': `${ICON_PATH}/dnd-kit.svg`,
  'AWS Cognito': `${ICON_PATH}/aws-cognito.svg`,
  'OIDC': `${ICON_PATH}/oidc.svg`,
  'WebAuthn': `${ICON_PATH}/webauthn.svg`,
  'ReactFlow': `${ICON_PATH}/reactflow.svg`,
  'Unity': `${ICON_PATH}/unity.svg`,
  'Photoshop': `${ICON_PATH}/photoshop-svgrepo-com.svg`,
  'Illustrator': `${ICON_PATH}/adobe-illustrator-svgrepo-com.svg`,
  'After Effects': `${ICON_PATH}/aftereffects-svgrepo-com.svg`,
  'Blender': `${ICON_PATH}/blender-svgrepo-com.svg`,
  'Maya': `${ICON_PATH}/Maya-Logo--Streamline-Ultimate.png`,
  'WebStorm': `${ICON_PATH}/webstorm-svgrepo-com.svg`,
  'Visual Studio': `${ICON_PATH}/visual-studio.svg`,
  'SJCL': `${ICON_PATH}/sjcl.svg`,
  'QR / WebAuthn': `${ICON_PATH}/webauthn.svg`,
  'TensorFlow': `${ICON_PATH}/tensorflow.svg`,
  'Adyen Payment System': `${ICON_PATH}/adyen.svg`,
  'jQuery': `${ICON_PATH}/jquery.svg`,
  'Web Development': `${ICON_PATH}/web-dev.svg`,
};
